### ISSUE TITLE
[Proposal] Change the 'to' param to be default

### ISSUE THREAD

**Issue by joecohens** [notifymehq/notifyme#14]
`$notifyme->driver('slack')->notify('You did it!', ['to' => '#everybody']);` => `$notifyme->driver('slack')->notify('You did it!', '#everybody');`

**Comment by jbrooksuk** [comment]
Yes!

**Comment by GrahamCampbell** [comment]
Maybe a different approach would work?

```
$notifyme->driver('slack')->notify()->message('You did it!')->to('#everybody')->send();
```

NB, the notify function would return a new object that can has setter methods as used here, and a send method.

**Comment by joecohens** [comment]
The only problem is that the "$to" param most of the times is required. I know you can validate on chaining but don't know if it would feel natural.

**Comment by GrahamCampbell** [comment]
We recently switched to it in factory muffin for the definitions, but it might not make sense here if you only plan to have a message and a "to". The method I'm proposing would be overkill in that case.

**Comment by joecohens** [comment]
Yeah for now it's only the `message` and the `to`, but I guess we can do that for extra params or overrides.

**Comment by GrahamCampbell** [comment]
Nah, your way is better. I actually have a better idea...

**Comment by GrahamCampbell** [comment]
Why not check if the second param is an array, If it is, use the current processing. If it is a string, treat it as if it were an array with the to key.

**Comment by joecohens** [comment]
Yeah that's better :)

**Comment by vinkla** [comment]
What if we want to send out to multiple users? For services that doesn't support sending to a single user? Maybe there should be a `notifyAll` method or something similar. Maybe this isn't the purpose of the library? What do you guys think?
