### ISSUE TITLE
Split current gateways to packages

### ISSUE THREAD

**Issue by joecohens** [notifymehq/notifyme#15]

**Comment by jbrooksuk** [comment]
If you make one how you'd like it:

- Readme
- PSR-4
- Docs

etc, I can do some too.

**Comment by GrahamCampbell** [comment]
Ok, so after #30 has been reviewed and merged, I can get to work on this. NB, I've already created 8 separate repos for our current gateways.

**Comment by frankdejonge** [comment]
As somebody who has recently (vert recently) moved from a "contain" all package to separate adapters (gateways or w/e). Do this as quick as you can. It's can be a massive undertaking.
