### ISSUE TITLE
What other services would you like to see on Notifyme?

### ISSUE THREAD

**Issue by joecohens** [notifymehq/notifyme#2]
Love to hear some suggestions and we are accepting all PR for new services :)

**Comment by jbrooksuk** [comment]
- WhatsApp
- Yo

**Comment by GrahamCampbell** [comment]
Hmm. What about supporting email notifications. That could be done easily through illuminate/mail.

**Comment by GrahamCampbell** [comment]
Also, once we get a laravel 5 version of this package, I'm probably going to get styleci to use it. :)

**Comment by GrahamCampbell** [comment]
What about supporting amazon's message stuff too?

**Comment by joecohens** [comment]
@GrahamCampbell :+1: Yeah I had mail in mind :)

@jbrooksuk Do you know if WhatsApp has an integration?

**Comment by joecohens** [comment]
That would be awesome!!!!

**Comment by GrahamCampbell** [comment]
http://aws.amazon.com/ses/

**Comment by GrahamCampbell** [comment]
http://aws.amazon.com/sns/

**Comment by joecohens** [comment]
Do you know if there is info about developing L5 packages yet?

**Comment by GrahamCampbell** [comment]
It's pretty much the same.

**Comment by GrahamCampbell** [comment]
In the case of this package, there are no changes needed.

**Comment by joecohens** [comment]
Perfect so maybe I can update the composer.json to require also 5.0.

**Comment by GrahamCampbell** [comment]
Yeh. "4.2.*|5.0.*".

**Comment by GrahamCampbell** [comment]
TBH, are you sure this doesn't work on 4.1 too. It might be an idea to do: "~4.1|~5.0".

**Comment by joecohens** [comment]
I guess it can work also on 4.1 updating...

**Comment by joecohens** [comment]
Updated https://github.com/dinkbit/notifyme/commit/2d0190c049484569bf6ff75b5218671efca7c2bc

**Comment by jbrooksuk** [comment]
Intercom?

**Comment by joecohens** [comment]
Upcoming integrations https://github.com/dinkbit/notifyme/commit/56b05dee16c815a256d2e7a5ea7d099fd70f6bda

**Comment by rscafi** [comment]
Perhaps [Pushbullet](https://www.pushbullet.com/)?

**Comment by jbrooksuk** [comment]
Pushover too.

**Comment by jbrooksuk** [comment]
APNS?

**Comment by GrahamCampbell** [comment]
Pubnub?

**Comment by GrahamCampbell** [comment]
I think we're getting a point where it would make more sense to move notifyme to it's own organisation, and have separate repos for each integration, whereby each integration is able to require it's own dependences, and they all depend on the core pacakge.

**Comment by joecohens** [comment]
Yeah that might be a good idea, since now I'm making each integration lightweight with out dependencies.

**Comment by GrahamCampbell** [comment]
Do you want to get started on that now? I can give you a hand. :)

**Comment by GrahamCampbell** [comment]
Since this package is so new, we can probably get away with renaming it on packagist too.

**Comment by GrahamCampbell** [comment]
You can just delete it and re-add it after changing it's name.

**Comment by joecohens** [comment]
I am not such a fan of the packages with many dependencies, but if you think it would help grow the implementations we can make the change now :)

**Comment by joecohens** [comment]
`notifyme` org it's in use :( .  https://github.com/notifyme-php

**Comment by jbrooksuk** [comment]
Will help when I have some time :)

**Comment by GrahamCampbell** [comment]
> I am not such a fan of the packages with many dependencies

This way we end up with fewer dependencies, and can test different package versions. For example, if we keep it in one sdk, we are forced to use either aws sdk v2 or aws sdk v3, and can't have separate support for both.

**Comment by GrahamCampbell** [comment]
@joecohens Contact github support and ask them to release the name for you. GitHub does not allow name-parking.

**Comment by GrahamCampbell** [comment]
> GitHub account name squatting is prohibited. Inactive accounts may be renamed or removed by GitHub staff at their discretion. You can examine an account's public profile to see if there's recent activity and request that support release a name for you, but keep in mind that not all activity on GitHub is publicly visible. Staff will not remove or rename any active account.

> GitHub account names are provided on a first-come, first-served basis, and are intended for immediate and active use. Account names may not be inactively held for future use.

> Attempts to sell, buy, or solicit other forms of payment in exchange for account names are prohibited and may result in permanent account suspension.

**Comment by rscafi** [comment]
I wanna help too. I can try to make pushbullet integration as soon as you guys prepare everything and show the way.

**Comment by jbrooksuk** [comment]
It may be a private repo.

**Comment by joecohens** [comment]
@jbrooksuk I was hopping you do :)

@rscafi Awesome!!! 

@GrahamCampbell Thanks I'll contact them!

**Comment by GrahamCampbell** [comment]
> It may be a private repo.

Yeh, the github staff can check if it's truly unused or not.

**Comment by Purus** [comment]
If there is some documentation to start with, I would love to jump in and contribute too.

**Comment by GrahamCampbell** [comment]
I totally changed how everything worked yesterday. Docs will come soonish.

**Comment by jeanfrancis** [comment]
Plivo

**Comment by jeanfrancis** [comment]
TelAPI

**Comment by jeanfrancis** [comment]
pump.io

**Comment by Grummfy** [comment]
xmpp => jabber => "google talk"/hangout

**Comment by jbrooksuk** [comment]
I've created an [irc](https://github.com/notifymehq/irc) repo. Please do contribute :)

**Comment by jbrooksuk** [comment]
Also [xmpp](https://github.com/notifymehq/xmpp)
