### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jbrooksuk** [notifymehq/notifyme#25]
How are you guys testing the gateways? Do you have a demo app or something?

**Comment by joecohens** [comment]
Hey! Yeah I have a Laravel installation only for contrib and test packages, there are two ways to do it, if you use Larave 4 you can use the workbench clone there and work, in 5 you can composer install or clone to the vendor folder and work there. For now it's the only ways I found :)

**Comment by jbrooksuk** [comment]
Workbench. Got it :)
