### ISSUE TITLE
Don't Use The Services Config

### ISSUE THREAD

**Issue by GrahamCampbell** [notifymehq/notifyme#27]
I propose we roll with our own config and use my manager package. That way we can have multiple connections to each driver.

~~Also, I think we should only support laravel 5. That would make things much simpler.~~

**Comment by jbrooksuk** [comment]
Can we only support L5 once Cachet is on L5?

**Comment by GrahamCampbell** [comment]
Sorry, the info posted here is already out of date. We decided in the other issue that we'd be maintaining both a laravel 4 bridge and a laravel 5 bridge. :)
