### ISSUE TITLE
Re-Add The Documentation

### ISSUE THREAD

**Issue by GrahamCampbell** [notifymehq/notifyme#41]

**Comment by jbrooksuk** [comment]
I wonder if we should check out ReadMe.io again?

**Comment by GrahamCampbell** [comment]
Probably a good idea. I also meant even add the basic install instructions too. :)

**Comment by jbrooksuk** [comment]
Ah of course.

**Comment by syrakozz** [comment]
+1

**Comment by Purus** [comment]
This repo interests me.. but not sure what it really does. Any docs will be helpful.

**Comment by jbrooksuk** [comment]
Yeah, we'll get docs done once we get a bit of time :)

@joecohens, @GrahamCampbell and myself are all really busy working on two huge projects at the moment, so we're lacking a bit of time I'm afraid.

I advise you have a play and check out the tests.

**Comment by Grummfy** [comment]
@Purus now the readme have an example
