### ISSUE TITLE
Suggest packages

### ISSUE THREAD

**Issue by jbrooksuk** [notifymehq/notifyme#44]
We can use the [suggest](https://getcomposer.org/doc/04-schema.md#suggest) key to show all of the notiifyme packages that are available.

**Comment by GrahamCampbell** [comment]
Yeh, forgot to do that. Thanks.

**Comment by joecohens** [comment]
Done :) https://github.com/notifymehq/notifyme/commit/03f114da3aa48997ad7e0f82f52657612022dd8f
