### ISSUE TITLE
Two way communications

### ISSUE THREAD

**Issue by jeanfrancis** [notifymehq/notifyme#46]
notifyme only supports one way communications ?

**Comment by GrahamCampbell** [comment]
Yes, that's true. How would you suggest we go about the reverse?

**Comment by jbrooksuk** [comment]
You'd have to get other services to send info back, to an endpoint.

**Comment by GrahamCampbell** [comment]
Yeh, exactly, and there's no framework agnostic way to do that.

**Comment by jbrooksuk** [comment]
Spot on. This isn't something a framework handles per-se. There may be functionality within the library to handle a request, but it wouldn't be able to just handle the HTTP side of things.

**Comment by GrahamCampbell** [comment]
I guess. We could do something that assume symfony classes? We could have a layer that accepts a symfony request class, and will throw symfony's http exceptions. Then we could have another layer underneath that that's more basic, and throws notifyme exceptions (the symfony layer will call this under the hood).

That way people using symfony/laravel/other frameworks using symfony components can use the more complete layer and just deal with the routing themselves. People using other frameworks can use the more general layer.

**Comment by GrahamCampbell** [comment]
No plans for this.
