### ISSUE TITLE
Can it be used without Composer

### ISSUE THREAD

**Issue by Coriou** [NotifyMeHQ/notifyme#66]
Hello,

This package looks awesome and spot on what I need for an older project of mine. I have a major problem though: I don't use Composer (and I don't plan to for this project).

Is there I can manually make this work ? I have tried including all files manually but not only that's pretty bad design, it just doesn't work properly of course.

Thank you :)

**Comment by GrahamCampbell** [comment]
Should be possible.

> that's pretty bad design

It should be easy to hijack only composer's autoloading if you want it.
