### ISSUE TITLE
Unable to install via composer using README.md instructions

### ISSUE THREAD

**Issue by Fuitad** [NotifyMeHQ/notifyme#67]
Running the command "composer require notifymehq/notifyme" in a brand new project returns the following eror:

    [InvalidArgumentException]
    Could not find package notifymehq/notifyme at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Same issue when running composer update with a composer.json with only this:

```
{
    "require": {
        "notifymehq/notifyme": "^1.0"
    }
}
```

```
$ composer --version
Composer version 1.0-dev (6eb50623e6e00bac4ed893802836e50b62c83434) 2016-02-08 19:03:10
```

**Comment by GrahamCampbell** [comment]
The error message you've posted tells you how to fix it.

**Comment by GrahamCampbell** [comment]
We've not tagged a stable release yet, so you need to lower minimum-stability.

**Comment by Fuitad** [comment]
This is correct and I understood that part. I was only pointing out that a less experienced user that would attempt to install your package by following your instructions would hit a wall. That's all.
