### ISSUE TITLE
Make package framework agnostic

### ISSUE THREAD

**Issue by joecohens** [notifymehq/notifyme#7]
https://github.com/dinkbit/notifyme/issues/6

**Comment by GrahamCampbell** [comment]
It already is framework agnostic though? We only require a very small dependency.

**Comment by joecohens** [comment]
Well that's right anyone could use it, the only thing missing is a Factory that can be used with out Laravel am I right?

**Comment by GrahamCampbell** [comment]
Just abstract the factory bit of the manager to a factory class then, and have the manager call it.

**Comment by joecohens** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I do this in a lot of my packages. I also use my own better manager class that behaves more like laravel's database manager and allows multiple connections to each driver.

**Comment by GrahamCampbell** [comment]
Two example packages:
* https://github.com/GrahamCampbell/Laravel-Flysystem
* https://github.com/GrahamCampbell/Laravel-DigitalOcean

**Comment by GrahamCampbell** [comment]
Oh yeh, and they're using https://github.com/GrahamCampbell/Laravel-Manager under the hood.

**Comment by joecohens** [comment]
Excellent! I've told you, you're a machine :))))

**Comment by GrahamCampbell** [comment]
lol

**Comment by GrahamCampbell** [comment]
Got a better idea. Move the laravel service provider and manager to another package. :)

**Comment by GrahamCampbell** [comment]
`notifyme-laravel`
